# Generated by Django 4.1.2 on 2022-10-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_image_tag_remove_comment_image_remove_post_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tags',
            field=models.ManyToManyField(blank=True, to='social.tag'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='social.tag'),
        ),
    ]
